In [2]:
import numpy as np
import scipy.stats as stats

In [9]:
n=3000
p = 0.064
z = 0.93
z93 = stats.norm.ppf((1+z)/2)
err = z93*np.sqrt((p*(1-p))/n)
print("Error:", err)
interval = p+np.array([-err, err])
interval

Error: 0.008096625783992643


array([0.05590337, 0.07209663])

In [14]:
n = 60
mu = 50
std = 10.2
z995 = stats.t.ppf((1+0.99)/2, n-1)
err = z995*np.sqrt((std**2)/n)
interval = mu+np.array([-err, err])
interval

array([46.49495791, 53.50504209])

In [35]:
n=400
p = 0.46
z95 = stats.norm.ppf((1+0.9)/2)
err = z95*np.sqrt((p*(1-p))/n)
interval = p+np.array([-err, err])
interval

array([0.41901046, 0.50098954])

In [33]:
N = 64
p = 41/N
z975 = 1.96
err = 0.05
n = (p*(1-p))/((err)/z975)**2
z975*np.sqrt((p*(1-p))/380)

0.04824364859682785

In [13]:
n = 100
X_bar = 27.89
Y_bar = 74.76
var_x = 4601.32
var_y = 270.77
z95 = stats.norm.ppf((1+0.9)/2)
err = z95*np.sqrt((var_x+var_y)/(n))
interval = (X_bar-Y_bar)+np.array([-err, err])
var_interval = [(var_y/var_x)*stats.f.ppf((1-.9)/2, n-1, n-1), (var_y/var_x)*stats.f.ppf((1+.9)/2, n-1, n-2)]
interval, err, Y_bar-X_bar, var_interval, stats.f.ppf((1-.9)/2, n-1, n-1), stats.f.ppf((1+.9)/2, n-1, n-2)

(array([-58.35113723, -35.38886277]),
 11.481137229065647,
 46.870000000000005,
 [0.042212031128112726, 0.0821186766976654],
 0.7173285927924351,
 1.3954807011947474)