In [2]:
import scipy.stats as stats
import numpy as np
import pandas as pd

<img src=".\Images\Punto1.jpg" width="50%"/>

In [122]:
## Punto 1
DATA1 = pd.read_csv('datos.csv')
n = len(DATA1)
mean = DATA1.mean()
std = DATA1.std()
alpha = 0.03
z = stats.t.ppf(1-alpha/2, n-1)
err = z * std/np.sqrt(n)
interval = mean[0] +np.array([-err, err])

print(interval)

[[5.54472305]
 [6.53527695]]


<img src=".\Images\Punto2.jpg" width="50%"/>

In [124]:
## Punto 2
p = 72/90
err = stats.norm.ppf(1-(0.02)/2)*np.sqrt((p*(1-p))/90)
interval = p+np.array([-err,err])
interval

array([0.70191256, 0.89808744])

<img src=".\Images\Punto3.jpg" width="50%"/>

In [127]:
## Punto 3
px = 318/822
py = 232/591
p = px-py
alpha = 0.02
z = stats.norm.ppf(1-alpha/2)
err = z*np.sqrt((px*(1-px)/822)+((py*(1-py)/591)))
interval = p+np.array([-err,err])
interval

array([-0.0668922 ,  0.05550484])

<img src=".\Images\Punto4.jpg" width="50%"/>

In [141]:
import math
## Punto 4
n1 = 91
n2 = 103
xb1 = 20.5
xb2 = 16.1
s1 = 4
s2 = 10.6
alpha=0.09
####################################################
est = s1/s2
p1 = stats.f.cdf(est, 90, 102)
p_value_var = 2*min(p1, 1-p1)
print("Valor p de la varianza:",p_value_var)
if p_value_var < alpha:
	print('Se rechaza la hipotesis nula. Las varianzas son heterosedásticas.')
else:
	print('No se rechaza la hipotesis nula. Las varianzas son homosedásticas.')

print('-----------------------------------------------------')
################
# Parte 2
################
# est = (16.9-26.7)/(np.sqrt((1/93)+(1/84))*np.sqrt((92*10.3+83*8.4)/(93+84-2)))
est = (xb1-xb2- 0)/np.sqrt(s1/n1 + s2/n2)
# reject_region = stats.t.ppf(1-0.01/2, 92+84-2)
f = (s1/n1 + s2/n2)**2/((s1/n1)**2/(n1-1) + (s2/n2)**2/(n2-1))
reject_region = stats.t.ppf(1-alpha/2, round(f))
p_value = 2*min(stats.t.cdf(est, f-1), 1-stats.t.cdf(est, f-1))
print("Estadístico de prueba:",est)
print("Región de rechazo:",reject_region)
print("Valor p:",p_value)
if p_value < alpha:
	print('Se rechaza la hipotesis nula. No se entrega credito a los dos.')
else:
	print('No se rechaza la hipotesis nula. Se otorga crédito a los dos.')

Valor p de la varianza: 3.928830758223898e-06
Se rechaza la hipotesis nula. Las varianzas son heterosedásticas.
-----------------------------------------------------
Estadístico de prueba: 11.48122167962623
Región de rechazo: 1.7049992328415078
Valor p: 0.0
Se rechaza la hipotesis nula. No se entrega credito a los dos.


<img src=".\Images\Punto5.jpg" width="50%"/>

In [132]:
## Punto 5
DATA2 = pd.read_csv('datos_brutos1.csv', encoding='utf-8')
n = len(DATA2)
## Hacer tabla de frecuencias facultad/empleo
freq = DATA2.groupby(['facultad','empleo']).size().reset_index(name='count')
freq = freq.pivot(index='facultad', columns='empleo', values='count')
freq.columns = DATA2.empleo.unique()
freq, n

(            Desempleado  Formal  Informal
 facultad                                 
 Ciencias             68      14        68
 Ingeniería           22       6        13
 Medicina             65      19        73,
 348)